DEFAULT_CONFIG_FOLDER = "/configuration"
DEFAULT_INPUT_STREAM_PORT = 9999
DEFAULT_OUTPUT_STREAM_PORT = 9999

# Configuration section names.
CONFIG_SECTION_FREQUENCY_MAPPING = "frequency_mapping"
CONFIG_SECTION_FREQUENCY = "frequency"
CONFIG_SECTION_DEVICES = "devices"

# Order of channels specified inside each device.
CONFIG_ORDER_CHANNEL_DATA = 0
CONFIG_ORDER_CHANNEL_BG_DATA = 1
CONFIG_ORDER_CHANNEL_DATA_TRIG = 2
CONFIG_ORDER_CHANNEL_BG_DATA_TRIG = 3
