DEFAULT_CONFIG_FOLDER = "/configuration"
DEFAULT_INPUT_STREAM_PORT = 9999
DEFAULT_OUTPUT_STREAM_PORT = 9999

# Configuration section names.
CONFIG_SECTION_FREQUENCY_MAPPING = "frequency_mapping"
CONFIG_SECTION_FREQUENCY = "frequency"
CONFIG_SECTION_DEVICES = "devices"

# Channel property names.
CONFIG_CHANNEL_NAME = "channel_name"
CONFIG_CHANNEL_NUMBER = "channel_number"
CONFIG_CHANNEL_PVS = "channel_pvs"

# Order of channels specified inside each device.
CONFIG_CHANNEL_ORDER_DATA = 0
CONFIG_CHANNEL_ORDER_BG_DATA = 1
CONFIG_CHANNEL_ORDER_DATA_TRIG = 2
CONFIG_CHANNEL_ORDER_BG_DATA_TRIG = 3
