package:
    name: frontend_digitizers_calibration
    version: 2.0.0

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - mflow >=0.0.26
        - bsread >=0.9.13
        - pyepics

build:
  entry_points:
    - calibrate_digitizer = frontend_digitizers_calibration.scripts.calibrate_digitizer:main

about:
    home: https://github.com/datastreaming/frontend_digitizers_calibration
