package:
    name: frontend_digitizers_calibration
    version: 0.0.3

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bsread >=0.9.12
        - pyepics

build:
  entry_points:
    - calibrate_pbps = frontend_digitizers_calibration.calibrate_pbps:main

about:
    home: https://git.psi.ch/controls_highlevel_applications/frontend_digitizers_calibration 
