package:
    name: frontend_digitizers_calibration
    version: 1.1.0

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - bsread >=0.9.12
        - pyepics

build:
  entry_points:
    - calibrate_digitizer = frontend_digitizers_calibration.scripts.calibrate_digitizer:main

about:
    home: https://git.psi.ch/controls_highlevel_applications/frontend_digitizers_calibration 
